### ISSUE TITLE
Remove nooitaf:semantic-ui-less from atmosphere?

### ISSUE THREAD

**Issue by splendido** [nooitaf/meteor-semantic-ui-less#7]
Hello @nooitaf!

Do you agree it might be worth removing the package from atmosphere?

See the 'Removing your package` section in the [Publishing](https://atmospherejs.com/i/publishing) page.
This is to keep our project folder as clean as possible and let new developers find packages at the first attempt.

Thanks,
Luca

**Comment by nooitaf** [comment]
agree, it's hidden

**Comment by splendido** [comment]
tnx!
